# development postgres database
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: munch
      POSTGRES_PASSWORD: munch
      POSTGRES_DB: munch
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  db:
  redis:
    driver: local
