# development postgres database
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: munch
      POSTGRES_PASSWORD: munch
      POSTGRES_DB: munch
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
